#!/bin/sh

# TODO: Improve sorting

database="$HOME/.local/share/databases/pronunciations.db"
alias loc='locate -d "$database"'

searchWord=$(xclip -o | sed 's/^ *//; s/ *$//;')
# If an argument is passed, use kana conversion instead
[ -n "$1" ] && searchWord=$(yomi "$searchWord")

# sort files by their length
results=$(loc "$searchWord")
selection="$(sed 's|^.*/pronunciations/||' <<< "$results" | awk '{ print length, $0 }' | sort -n -s | cut -d" " -f2- | dmenu -l 8)"

[ -z $selection ] && exit 1

file=$(grep -F -m 1 "$selection" <<< "$results")
ffplay -loglevel quiet -autoexit -nodisp "$file"
xclip -in -selection clipboard -target "text/uri-list" <<< "file://$file"
exit 0
